security:
    oauth2:
      client:
        client-id: tonr
        client-secret: secret
      resource:
        token-info-uri: http://localhost:8080/oauth/check_token
server.port: 8084

debug: true