package com.zhou.test.mapper;

import com.zhou.test.pojo.MenuOfResource;
import com.zhou.test.pojo.MenuOfResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MenuOfResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_of_resource
     *
     * @mbg.generated Fri Jul 05 19:09:18 CST 2019
     */
    long countByExample(MenuOfResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_of_resource
     *
     * @mbg.generated Fri Jul 05 19:09:18 CST 2019
     */
    int deleteByExample(MenuOfResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_of_resource
     *
     * @mbg.generated Fri Jul 05 19:09:18 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_of_resource
     *
     * @mbg.generated Fri Jul 05 19:09:18 CST 2019
     */
    int insert(MenuOfResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_of_resource
     *
     * @mbg.generated Fri Jul 05 19:09:18 CST 2019
     */
    int insertSelective(MenuOfResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_of_resource
     *
     * @mbg.generated Fri Jul 05 19:09:18 CST 2019
     */
    List<MenuOfResource> selectByExampleWithRowbounds(MenuOfResourceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_of_resource
     *
     * @mbg.generated Fri Jul 05 19:09:18 CST 2019
     */
    List<MenuOfResource> selectByExample(MenuOfResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_of_resource
     *
     * @mbg.generated Fri Jul 05 19:09:18 CST 2019
     */
    MenuOfResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_of_resource
     *
     * @mbg.generated Fri Jul 05 19:09:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") MenuOfResource record, @Param("example") MenuOfResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_of_resource
     *
     * @mbg.generated Fri Jul 05 19:09:18 CST 2019
     */
    int updateByExample(@Param("record") MenuOfResource record, @Param("example") MenuOfResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_of_resource
     *
     * @mbg.generated Fri Jul 05 19:09:18 CST 2019
     */
    int updateByPrimaryKeySelective(MenuOfResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_of_resource
     *
     * @mbg.generated Fri Jul 05 19:09:18 CST 2019
     */
    int updateByPrimaryKey(MenuOfResource record);
}